version: '3'

volumes:
  portainer-data:
    driver: local
    
services:
  portainer:
    container_name: portainer
    restart: always
    image: 'portainer/portainer-ce:latest'
    ports:
      - '9000:9000'
      - '9443:9443'
      - '8000:8000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/protainer:/data
